---
development:
  dialect: postgres
  database: buffalo_test_examples_development
  user: postgres
  password: postgres
  host: 127.0.0.1
  pool: 5

test:
  dialect: {{envOr "TEST_DATABASE_DIALECT" "postgres"}}
  database: {{envOr "TEST_DATABASE_DB" "buffalo_test_examples_test"}}
  user: {{envOr "TEST_DATABASE_USER" "postgres"}}
  password: {{envOr "TEST_DATABASE_PASS" "postgres"}}
  host: {{envOr "TEST_DATABASE_HOST" "127.0.0.1"}}
  pool: {{envOr "TEST_DATABASE_POOL" "5"}}

production:
  url: {{env "DATABASE_URL"}}
