---
development:
  url: {{env "DEV_DATABASE_URL"}}
  # dialect: {{envOr "DATABASE_DIALECT" "postgres"}}
  # database: {{envOr "DATABASE_DB" "buffalo_test_examples_development"}}
  # user: {{envOr "DATABASE_USER" "postgres"}}
  # password: {{envOr "DATABASE_PASS" "postgres"}}
  # host: {{envOr "DATABASE_HOST" "127.0.0.1"}}
  # pool: {{envOr "DATABASE_POOL" "5"}}

test:
  url: {{env "TEST_DATABASE_URL"}}
  # dialect: {{envOr "TEST_DATABASE_DIALECT" "postgres"}}
  # database: {{envOr "TEST_DATABASE_DB" "buffalo_test_examples_test"}}
  # user: {{envOr "TEST_DATABASE_USER" "postgres"}}
  # password: {{envOr "TEST_DATABASE_PASS" "postgres"}}
  # host: {{envOr "TEST_DATABASE_HOST" "127.0.0.1"}}
  # pool: {{envOr "TEST_DATABASE_POOL" "5"}}

production:
  url: {{env "DATABASE_URL"}}
