version: '3.1'

services:
  web:
    build: .
    ports:
      - "3000"
    environment:
      - ADDR=0.0.0.0
      - PORT=3000
      - GO_ENV=test
      - TEST_DATABASE_URL=postgres://postgres:postgres@db:5432/buffalo_test_examples_test?sslmode=disable
      - TEST_DATABASE_HOST=db
      - TEST_DATABASE_DB=buffalo_test_examples_test
      - TEST_DATABASE_USER=postgres
      - TEST_DATABASE_PASS=postgres
    depends_on:
      - db
  
  migration:
    build:
      context: .
      target: builder
    command: >
      /bin/sh -c '
        set -eo xtrace

        wait-for -timeout 7s tcp:db:5432

        buffalo db migrate up -e test

        go run ./scripts/ready.go
      '
    environment:
      - TEST_DATABASE_URL=postgres://postgres:postgres@db:5432/buffalo_test_examples_test?sslmode=disable
      - TEST_DATABASE_DIALECT=postgres
      - TEST_DATABASE_HOST=db
      - TEST_DATABASE_DB=buffalo_test_examples_test
      - TEST_DATABASE_USER=postgres
      - TEST_DATABASE_PASS=postgres
    depends_on:
      - db

  db:
    image: postgres:13.7
    restart: always
    environment:
      POSTGRES_DB: buffalo_test_examples_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  gherkin:
    build:
      context: .
      dockerfile: tests.dockerfile
    command: >
      /bin/sh -c '
        set -eo xtrace

        wait-for -timeout 15s tcp:db:5432 http://migration:8080 http://web:3000

        pushd /project/test

        godog
      '
    volumes:
      - .:/project
    environment:
      - TEST_DATABASE_HOST=db
      - TEST_DATABASE_DB=buffalo_test_examples_test
      - TEST_DATABASE_USER=postgres
      - TEST_DATABASE_PASS=postgres
    depends_on:
      - db
      - migration
      - web